examsystem/data/urls.py
#-*- coding: utf-8 -*- 
from django.conf.urls import url

from . import views

urlpatterns = [
    #common
    url(r'^welcome/$',views.welcome,name = 'welcome'),
    url(r'^HomePage/$',views.HomePage,name = 'HomePage'),
    url(r'^RegesteSuccess/$',views.RegesteSuccess,name = 'RegesteSuccess'),
    #user
    url(r'^StudentUpdate/$', views.StudentUpdate, name='StudentUpdate'),
    url(r'^TeacherUpdate/$', views.TeacherUpdate, name='TeacherUpdate'),
    url(r'^ChooseTeacher/$',views.ChooseTeacher,name = 'ChooseTeacher'),
    url(r'^StudentList/$',views.StudentList,name = 'StudentList'),
    url(r'^NewUser/$',views.NewUser,name = 'NewUser'),
    url(r'^Login/$',views.Login,name = 'Login'),

    #url(r'^UserDetail/$',views.UserDetail,name = 'UserDetail'),
    url(r'^UserDetail/(?P<pk>[^/]+)/$',views.UserDetail,name = 'UserDetail'),
    url(r'^Logout/$',views.Logout,name = 'Logout'),
    #questions
    url(r'^choiceQ/$', views.get_choicequestion, name='get_choicequestion'),
    url(r'^fillQ/$', views.get_fillquestion, name='get_fillquestion'),
    url(r'^tfQ/$', views.get_tfquestion, name='get_tfquestion'),
    url(r'^saQ/$', views.get_saquestion, name='get_saquestion'),
    url(r'^Questionlist/$', views.Questionlist, name='Questionlist'),
    #url(r'^Questionlist/(?P<point>[^/]+)/(?P<style>[a-z]+)/$', views.Questionlist, name='Questionlist'),
   
    #exam   
    url(r'^AddExam/$',views.AddExam,name = 'AddExam'),
    url(r'^AddExam/(?P<pk>[^/]+)/Questionlist/$',views.SelectQuestion,name = 'SelectQuestion'),
    url(r'^AddExam/(?P<pk>[^/]+)/Questionlist/(?P<point>[^/]+)/(?P<style>[a-z]+)/$', views.SelectQuestion, name='SelectQuestion'),
    url(r'^SetMark/(?P<pk>[^/]+)/SetMark$',views.SetMark,name = 'SetMark'),
    url(r'^ExamList/$',views.ExamList,name = 'ExamList'),
    url(r'^SetExamVisiable/(?P<pk>[0-9]+)/$',views.SetExamVisiable,name = 'SetExamVisiable'),
    url(r'^ExamDetail/(?P<pk>[0-9]+)/$',views.ExamDetail,name = 'ExamDetail'),
    #test
    url(r'^NewTest/$',views.NewTest,name = 'NewTest'),
    url(r'^ChooseExam/(?P<pk>[0-9]+)/$',views.ChooseExam,name = 'ChooseExam'),
    url(r'^TestList/$',views.TestList,name = 'TestList'),
    url(r'^TestDetail/(?P<pk>[0-9]+)/$',views.TestDetail,name = 'TestDetail'),
    url(r'^TestLogList/$',views.TestLogList,name = 'TestLogList'),
    url(r'^AnswerTest/(?P<pk>[0-9]+)/$',views.AnswerTest,name = 'AnswerTest'),
    url(r'^TestReport/(?P<pk>[0-9]+)/$',views.TestReport,name = 'TestReport'),
    #answer
    url(r'^AnswerExam/(?P<pk>[0-9]+)/$',views.AnswerExam,name = 'AnswerExam'),
    url(r'^verifyAnswer/(?P<pk>[0-9]+)/$',views.verify_Answer,name = 'verify_Answer'),
    url(r'^ExamResult/(?P<pk>[0-9]+)/$',views.ExamResult,name = 'ExamResult'),
    url(r'^ResultDetail/(?P<pk>[0-9]+)/$',views.ResultDetail,name = 'ResultDetail'),
    url(r'^JudgeAnswer/(?P<pk>[0-9]+)/$',views.JudgeAnswer,name = 'JudgeAnswer'),
    url(r'^ResultList/$',views.ResultList,name = 'ResultList'),
    ]

    #url(r'^SearchQuestion/$', views.SearchQuestion, name='search_question'),
    #url(r'^SearchQuestion/(?P<point>[^/]+)/(?P<style>[a-z]+)/(?P<pagenum>[0-9]+)/$', views.SearchQuestion, name='search_question'),

examsystem/examsystem/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from data.views import HomePage

urlpatterns = [
	url(r'^$', HomePage,name = 'HomePage'),
	url(r'^data/', include('data.urls',namespace = "data")),
    url(r'^admin/', include(admin.site.urls)),
]

examsystem/data/models.py
#-*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User,Group
# Create your models here.
#question
class ChoiceQuestion(models.Model):
	"""docstring for Question_select"""
	question_text = models.CharField(max_length=200)
	CHOICES = ( ('A','A'),
				('B','B'),
				('C','C'),
				('D','D'),
			  )
	ans = models.CharField(max_length = 1,choices = CHOICES)
	DIFFCULTYS= (('ez','easy'),
				 ('nm','normal'),
				 ('hd','hard'),
				)
	diffculty = models.CharField(max_length = 2,choices = DIFFCULTYS)
	date = models.DateTimeField('date input',auto_now = True)
	user = models.ForeignKey(User,null = True)
	def __unicode__(self):
		return self.question_text

class Choice(models.Model):
	"""docstring for ClassName"""
	question = models.ForeignKey(ChoiceQuestion)
	choice_text = models.CharField(max_length = 200)
	CHOICES = ( ('A','A'),
				('B','B'),
				('C','C'),
				('D','D'),
			  )
	number = models.CharField(max_length = 1,choices = CHOICES)
	def __unicode__(self):
		return self.choice_text

class FillQuestion(models.Model):
	question_text = models.CharField(max_length=200)
	ans = models.CharField(max_length = 200)
	DIFFCULTYS= (('ez','easy'),
				 ('nm','normal'),
				 ('hd','hard'),
				)
	diffculty = models.CharField(max_length = 2,choices = DIFFCULTYS)
	date = models.DateTimeField('date input',auto_now = True)
	user = models.ForeignKey(User,null = True)
	def __unicode__(self):
		return self.question_text

class TfQuestion(models.Model):
	question_text = models.CharField(max_length=200,verbose_name = '题干')
	ans = models.BooleanField(verbose_name = '答案')
	DIFFCULTYS= (('ez','简单'),
				 ('nm','普通'),
				 ('hd','困难'),
				)
	diffculty = models.CharField(max_length = 2,choices = DIFFCULTYS,verbose_name = '难度')
	date = models.DateTimeField('date input',auto_now = True)
	user = models.ForeignKey(User,null = True)
	def __unicode__(self):
		return self.question_text

class SAQuestion(models.Model):
	question_text= models.CharField(max_length = 200,verbose_name = '题干')
	ans = models.CharField(max_length = 200,verbose_name = '答案')
	DIFFCULTYS= (('ez','简单'),
				 ('nm','普通'),
				 ('hd','困难'),
				)
	diffculty = models.CharField(max_length = 2,choices = DIFFCULTYS,verbose_name = '难度')
	date = models.DateTimeField('date input',auto_now = True)
	user = models.ForeignKey(User,null = True)
	def __unicode__(self):
		return self.question_text

#point&subject
class Point(models.Model):
    name = models.CharField(max_length=50)
    parent = models.ForeignKey("self", blank=True, null=True, related_name="children")
    choicequestions= models.ManyToManyField(ChoiceQuestion,blank = True) 
    fillquestions = models.ManyToManyField(FillQuestion,blank = True) 
    tfquestions = models.ManyToManyField(TfQuestion,blank = True)
    saquestions = models.ManyToManyField(SAQuestion,blank = True)
    def __unicode__(self):
        return self.name

#exam
class Exam(models.Model):
	name = models.CharField(max_length=50,verbose_name = '名称')
	subject = models.ForeignKey(Point,verbose_name = '学科')
	DIFFCULTYS= (('ez','简单'),
				 ('nm','普通'),
				 ('hd','困难'),
				)
	diffculty = models.CharField(max_length = 2,choices = DIFFCULTYS,verbose_name = '难度')
	count = models.IntegerField(default = 100)
	choicequestions= models.ManyToManyField(ChoiceQuestion,through = 'ChoiceQuestionDetail',blank = True)
	fillquestions = models.ManyToManyField(FillQuestion,through = 'FillQuestionDetail',blank = True)
	tfquestions = models.ManyToManyField(TfQuestion,through = 'TfQuestionDetail',blank = True)
	saquestions = models.ManyToManyField(SAQuestion,through = 'SAQuestionDetail',blank = True)
	date = models.DateTimeField('date_input',auto_now = True)
	user = models.ForeignKey(User,null = True)
	state = models.BooleanField(default = False)
	def __unicode__(self):
		return self.name

class ChoiceQuestionDetail(models.Model):
	choicequestion = models.ForeignKey(ChoiceQuestion)
	exam = models.ForeignKey(Exam)
	mark = models.IntegerField()

class FillQuestionDetail(models.Model):
	choicequestion = models.ForeignKey(FillQuestion)
	exam = models.ForeignKey(Exam)
	mark = models.IntegerField()

class TfQuestionDetail(models.Model):
	tfquestion = models.ForeignKey(TfQuestion)
	exam = models.ForeignKey(Exam)
	mark = models.IntegerField()

class SAQuestionDetail(models.Model):
	saquestion = models.ForeignKey(SAQuestion)
	exam = models.ForeignKey(Exam)
	mark = models.IntegerField()
#test
class Test(models.Model):
	name = models.CharField(max_length = 50,verbose_name = '名称')
	user = models.ForeignKey(User)
	TYPE =(('homework','作业'),
			('exam','测试'))
	Type =  models.CharField(max_length = 10,choices = TYPE,verbose_name = '类别')
	exam = models.ForeignKey(Exam,null = True,default = None)
	students = models.ManyToManyField(User,through = 'TestLog',related_name = 'testlog')
	state = models.BooleanField(default =  False)
	date = models.DateTimeField(auto_now = True)
	def __unicode__(self):
		return self.name

#answer
class Answer(models.Model):
	exam = models.ForeignKey(Exam)
	choicequestion = models.ManyToManyField(ChoiceQuestion,through = 'ChoiceQuestionAns')
	fillquestion = models.ManyToManyField(FillQuestion,through = 'FillQuestionAns')
	Tfquestion = models.ManyToManyField(TfQuestion,through = 'TfQuestionAns')
	saquestion = models.ManyToManyField(SAQuestion,through = 'SAQuestionAns')
	user = models.ForeignKey(User,null = True)
	select_score = models.IntegerField(null=True,default= None)
	fill_score= models.IntegerField(null = True,default = None)
	tf_score= models.IntegerField(null = True,default = None)
	sa_score= models.IntegerField(null = True,default = None)
	score = models.IntegerField(null = True,default = None)
	state = models.BooleanField(default = True)
	test = models.ForeignKey(Test,null = True,default =  True)
	date = models.DateTimeField('date_input',auto_now = True)
	def __unicode__(self):
		return self.exam.name

class TestLog(models.Model):
	test = models.ForeignKey(Test)
	answer = models.ForeignKey(Answer,null =  True,default = None)
	student = models.ForeignKey(User,related_name = 'STUDENT')
	state = models.BooleanField(default = False)
	date = models.DateTimeField(auto_now = True)
	def __unicode__(self):
		return self.student.username

class ChoiceQuestionAns(models.Model):
	choicequestion = models.ForeignKey(ChoiceQuestion)
	answer = models.ForeignKey(Answer)
	ans = models.CharField(max_length = 2,null = True)
	state = models.NullBooleanField(null = True,default =None)

class FillQuestionAns(models.Model):
	fillquestion = models.ForeignKey(FillQuestion)
	answer = models.ForeignKey(Answer)
	ans = models.CharField(max_length = 100,null= True)
	state = models.NullBooleanField(null = True,default = None)

class TfQuestionAns(models.Model):
	Tfquestion = models.ForeignKey(TfQuestion)
	answer = models.ForeignKey(Answer)
	ans = models.NullBooleanField()
	state = models.NullBooleanField(null = True,default = None)

class SAQuestionAns(models.Model):
	saquestion = models.ForeignKey(SAQuestion)
	answer = models.ForeignKey(Answer)
	ans = models.CharField(max_length = 200,null = True)
	mark = models.IntegerField(default = 10)
	score = models.IntegerField(null = True)
	state = models.NullBooleanField(null = True,default = None)

#user
class Student(models.Model):
	name = models.CharField(max_length=10,null = True)
	user = models.ForeignKey(User,null = True)
	num = models.CharField(max_length=15,null = True)
	age = models.IntegerField(null = True)
	SEX =(('m','男'),('f','女'),)
	sex = models.CharField(max_length = 1,choices = SEX,null = True)
	birth = models.DateField(blank = True,null = True)
	COLLEGE = (('计算机','计算机学院'),('软件','软件学院'),)
	college = models.CharField(max_length = 10,choices = COLLEGE,null = True)
	tel = models.CharField(max_length = 15,blank = True,null = True)
	email =models.EmailField(blank = True,null = True)
	image = models.ImageField(blank = True)
	def __unicode__(self):
		if self.name == None:
			return 'NULL'
		return self.name

class Teacher(models.Model):
	name = models.CharField(max_length=10,null = True)
	user = models.ForeignKey(User,null = True)
	num = models.CharField(max_length=15,null = True)
	age = models.IntegerField(null = True)
	SEX =(('m','男'),('f','女'),)
	sex = models.CharField(max_length = 1,choices = SEX,null = True)
	birth = models.DateField(blank = True,null = True)
	COLLEGE = (('sc','计算机学院'),('sw','软件学院'),)
	college = models.CharField(max_length = 20,choices = COLLEGE,blank = True,null = True)
	tel = models.CharField(max_length = 15,blank = True,null = True)
	email =models.EmailField(blank = True,null = True)
	students = models.ManyToManyField(User,related_name = "students")
	def __unicode__(self):
		return self.name

examsystem/data/forms.py
#-*- coding: utf-8 -*- 
from django import forms
from django.forms import ModelForm
from django.forms.widgets import CheckboxSelectMultiple

from .models import *
from django.contrib.auth.models import Group

#QuestionForm
class ChoiceQuestionForm(forms.Form):
    point = forms.ModelChoiceField(label='知识点',queryset=Point.objects.all())
    question = forms.CharField(label='题干', max_length=100,widget=forms.Textarea(attrs={'cols':'110','rows':'5'}))
    choiceA = forms.CharField(label='A', max_length=100)
    choiceB = forms.CharField(label='B', max_length=100)
    choiceC = forms.CharField(label='C', max_length=100)
    choiceD = forms.CharField(label='D', max_length=100)
    CHOICES = ( ('A','A'),
				('B','B'),
				('C','C'),
				('D','D'),
			  )
    ans = forms.ChoiceField(label = '答案',choices = CHOICES)
    DIFFCULTYS= (('ez','简单'),
				 ('nm','普通'),
				 ('hd','困难'),
				)
    diffculty = forms.ChoiceField(label = '难度',choices = DIFFCULTYS)

class FillQuestionForm(forms.Form):
	point = forms.ModelChoiceField(label='知识点',queryset=Point.objects.all())
	question = forms.CharField(label='题干', max_length=100,widget=forms.Textarea(attrs={'cols':'110','rows':'5'}))
	ans =  forms.CharField(label='答案', max_length=100)
  	DIFFCULTYS= (('ez','简单'),
				 ('nm','普通'),
				 ('hd','困难'),
				)
	diffculty = forms.ChoiceField(label = '难度',choices = DIFFCULTYS)

class TfQuestionForm(ModelForm):
	point = forms.ModelChoiceField(label='知识点',queryset=Point.objects.all())
	class Meta:
		model = TfQuestion
		fields = ['question_text','ans','diffculty']
		widgets = {
         	'question_text':forms.Textarea(attrs={'cols':'110','rows':'5'})
        		}
class SAQuestionForm(ModelForm):
	point = forms.ModelChoiceField(label='知识点',queryset=Point.objects.all())
	class Meta:
		model = SAQuestion
		fields = ['question_text','ans','diffculty']
		widgets = {
         	'question_text':forms.Textarea(attrs={'cols':'110','rows':'5'})
        		}
class SearchQuestionForm(forms.Form):
	point = forms.ModelChoiceField(label='知识点',queryset=Point.objects.all(),required = False)
	STYLE = (('select','选择题'),('fill','填空题'),('tf','判断题'),('sa','简答题'))
	style = forms.ChoiceField(label = '题型',choices = STYLE)
	question_keyword = forms.CharField(label = '题目关键词',max_length = 100,required=False)

#exam
class AddExamForm(ModelForm):
	count = forms.IntegerField(label='总分')
	class Meta:
		model = Exam
		fields = ['name','subject','diffculty']
		'''widgets = {
            'fillquestions': CheckboxSelectMultiple(),
            'choicequestions':CheckboxSelectMultiple(),
        		}'''

class SearchExamForm(forms.Form):
	name = forms.CharField(label = '名称',max_length = 20,required = False)
	subject = forms.ModelChoiceField(label = '知识点',queryset = Point.objects.all(),required =False)
	DIFFCULTYS= (('ez','简单'),
				 ('nm','普通'),
				 ('hd','困难'),
				 ('all','全部')
				)
	diffculty = forms.ChoiceField(label = '难度',choices = DIFFCULTYS)
	state = forms.BooleanField(label = '是否可见',required = False)

class SearchAnswerForm(forms.Form):
	name = forms.CharField(label = '名称',max_length = 20,required = False)
	author = forms.CharField(label = '答题者',max_length = 20,required = False)

#test
class NewTestForm(ModelForm):
	class Meta:
		model = Test
		fields =['name','Type']

class TestSearchForm(forms.Form):
	name = forms.CharField(label = '名称',max_length = 50,required = False)
	user = forms.CharField(label = '使用者',max_length = 30,required = False)
	TYPE =(('homework','作业'),
			('exam','考试'))
	Type = forms.ChoiceField(label = '事件类型',choices = TYPE,required = False)
#user
class StudentSignInForm(forms.Form):
	name = forms.CharField(label='用户名', max_length=10)
	num = forms.CharField(label='学号', max_length=15)
	age = forms.IntegerField(label = '年龄')
	SEX =(('m','男'),('f','女'),)
	sex = forms.ChoiceField(label = '性别',choices = SEX)
	birth = forms.DateField(label ='生日',required=False)
	COLLEGE = (('计算机','计算机学院'),('软件','软件学院'),)
	college = forms.ChoiceField(label = '学院',choices = COLLEGE)
	tel = forms.CharField(label = '电话',max_length = 15,required=False)
	email =forms.EmailField(label = 'email',required=False)

class TeacherSignInForm(forms.Form):
	name = forms.CharField(label='用户名', max_length=10)
	num = forms.CharField(label='教职工号', max_length=15)
	age = forms.IntegerField(label = '年龄')
	SEX =(('m','男'),('f','女'),)
	sex = forms.ChoiceField(label = '性别',choices = SEX)
	birth = forms.DateField(label ='生日',required=False)
	COLLEGE = (('计算机','计算机学院'),('软件','软件学院'),)
	college = forms.ChoiceField(label = '学院',choices = COLLEGE)
	tel = forms.CharField(label = '电话',max_length = 15,required=False)
	email =forms.EmailField(label = 'email',required=False)

class NewUserSignInForm(forms.Form):
	username = forms.CharField(label = '用户名',max_length = 30)
	password = forms.CharField(label = '密码',max_length = 10,widget=forms.PasswordInput)
	GROUPS = (('teacher','教师'),('student','学生'))
	group = forms.ModelChoiceField(label = '身份',queryset=Group.objects.all())

class NewUserLoginForm(forms.Form):
	username = forms.CharField(label = '用户名',max_length = 30)
	password = forms.CharField(label = '密码',max_length = 10,widget=forms.PasswordInput)

class ChooseTeacherForm(forms.Form):
	name = forms.CharField(label = '姓名',max_length = 30 ,required=False)
	subject = forms.CharField(label = '学院',max_length = 30,required = False)

examsystem/templates/data/TestDetail.html
<!DOCTYPE html>
<html>
<head>
 <title></title>
 <!-- 新 Bootstrap 核心 CSS 文件 -->
 <link href="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">

 <!-- 可选的Bootstrap主题文件（一般不使用） -->
 <script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap-theme.min.css"></script>

 <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
 <script src="http://apps.bdimg.com/libs/jquery/2.0.0/jquery.min.js"></script>

 <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
 <script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js"></script>

</head>
<body>
{% extends 'data/base.html' %}
{%block content%}
<h1 class="text-center">事件信息</h1>
<ul class="list-inline text-center">
<li>名称:{{test.name}}</li>
<li>作者:{{test.user}}</li>
<li>类型:{{test.Type}}</li>
<li>日期:{{test.date}}</li>
<li>学生数目:{{testlogs|length}}</li>
</ul>
<h4>完成学生数:{{finish_student|length}}</h4>
<table class="table table-hover">
	{%if finish_student%}
	<tr>
		<th>学生姓名</th>
		<th>完成状态</th>
		<th>答案详情</th>
		<th>答案待判情况</th>
		<th>选项</th>
	</tr>
	{%endif%}
	{%for item in finish_student%}
	<tr>
		<td>{{item.student}}</td>
		<td>{{item.state|yesno:"已完成,未完成,Perhaps"}}</td>
		<td><a href="{%url 'data:ResultDetail' item.answer.id%}">答案详情</a></td>
		<td>{{item.answer.state|yesno:"已判,待判,Perhaps"}}</td>
		{%if not item.answer.state %}
		<td><a href="{%url 'data:JudgeAnswer' item.answer.id%}">点击判卷</td>
		{%else%}
		<td>unll</td>
		{%endif%}
	</tr>
	{%empty%}
	<p>暂时没有学生完成</p>
	{%endfor%}
</table>
<h4>未完成学生数:{{unfinish_student|length}}</h4>
<table class="table table-hover">
	<tr>
		<th>学生姓名</th>
		<th>完成状态</th>
	</tr>
	{%for item in unfinish_student%}
	<tr>
		<td>{{item.student}}</td>
		<td>{{item.state}}</td>
	</tr>
	{%empty%}
	<p>所有学生都已完成</p>
	{%endfor%}
</table>
{%endblock%}
</body>

examsystem/templates/data/base.html
<!DOCTYPE html>
<html>
<head>
 <title></title>
 <!-- 新 Bootstrap 核心 CSS 文件 -->
 <link href="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">

 <!-- 可选的Bootstrap主题文件（一般不使用） -->
 <script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/css/bootstrap-theme.min.css"></script>

 <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
 <script src="http://apps.bdimg.com/libs/jquery/2.0.0/jquery.min.js"></script>

 <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
 <script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js"></script>

</head>
<body>

 <div class="container">
  <div class="container">
   <div class="row">
    <div class="col-md-12">
      <nav class="navbar navbar-default" role="navigation">
       <div class="navbar-header">
         <h1>考试管理系统</h1>
       </div>
       <ul class="nav navbar-nav navbar-right">
         <li class="navbar-text">{{user.username}}您以{%if perms.data.add_choicequestion%}教师{%else%}学生{%endif%}的身份登录
           <a href="{%url 'data:Logout'%}">登出</a></li>
           <ul>
           </nav>


           <div class="row">
             <div class="col-md-3">
              <div class="panel panel-primary">
                <div class="panel-heading">
                  <h3 class="panel-title">active</h3>
                </div>
                <div class="panel-body">
                  <h4>题目管理</h4>
                  <ul>
                    {%if perms.data.add_choicequestion%}
                    <li><a href="{%url 'data:get_choicequestion'%}">选择题</a></li>
                    <li><a href="{%url 'data:get_fillquestion'%}">填空题</a></li>
                    <li><a href="{%url 'data:get_tfquestion'%}">判断题</a></li>
                    <li><a href="{%url 'data:get_saquestion'%}">简答题</a></li>
                    {%endif%}
                    <li><a href="{%url 'data:Questionlist'%}">题目列表</a></li>
                  </ul>
                  <h4>考试管理</h4>
                  <ul>
                    {%if perms.data.add_choicequestion%}
                    <li><a href="{%url 'data:AddExam'%}">添加考试</a></li>
                    <li><a href="{%url 'data:NewTest'%}">新事件</li>
                    {%endif%}
                    <li><a href="{%url 'data:ExamList'%}">考试列表</a></li>
                    {%if perms.data.add_choicequestion%}
                    <li><a href="{%url 'data:TestList'%}">事件列表</a></li>
                    {%else%}
                    <li><a href="{%url 'data:TestLogList'%}">相关事件记录</a></li>
                    {%endif%}
                  </ul>
                  <h4>考试结果</h4>
                  <ul>
                    <li><a href="{%url 'data:ResultList'%}">考试结果列表</a></li>
                    {%comment%}
                    <li><a href="{%url 'data:NewUser'%}">新用户</a></li>
                    <li><a href="{%url 'data:Login'%}">登入</a></li>
                    <li><a href="{%url 'data:AnswerExam' 1 %}">答卷</a></li>
                    {%endcomment%}
                  </ul>
                </div>
              </div>
              <div class="panel panel-primary">
                <div class="panel-heading">
                  <h3 class="panel-title">user</h3>
                </div>
                <div class="panel-body">
                  <ul>
                    <li><a href="{%url 'data:UserDetail' user.id%}">用户信息</a></li>
                    <li><a href="{%url 'data:Logout'%}">退出</a></li>
                    {%if perms.data.add_choicequestion%}
                    <li><a href="{%url 'data:TeacherUpdate'%}">教师信息更新</a></li>
                    <li><a href="{%url 'data:StudentList'%}">学生列表</a></li>
                    {%else%}
                    <li><a href="{%url 'data:StudentUpdate'%}">学生信息更新</a></li>
                    <li><a href="{%url 'data:ChooseTeacher'%}">教师选择</a></li>
                    {%endif%}
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-md-9">
                <div class="panel panel-success">
              
                <div class="panel-body">
                
                {%block content%}{%endblock%}
                </div>
              </div>
            </div>



         </div>
       </div>
     </div>
   </div>
 </div>



</body>
</html>